<a href="https://colab.research.google.com/github/matthewreader/continuous-learning/blob/main/books/deep-learning-with-pytorch/Deep_Learning_with_PyTorch_Chapter_3_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Create a tensor `a` from `list(range(9))`.  Predict and then check the size, offset, and stride.

In [15]:
import torch
a = torch.tensor(range(9))
print(a)
print(f'Size of a = {a.size()}')
print(f'Offset of a = {a.storage_offset()}')
print(f'Stride of a = {a.stride()}')

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
Size of a = torch.Size([9])
Offset of a = 0
Stride of a = (1,)


1a) Create a new tensor using `b = a.view(3, 3)`.  What does `view` do?  Check that a and b share the same storage.
* View reshapes a tensor, assuming that the shape given is compatable with the original tensor.
* We can check if tensors share the same memory address using `torch.tensor.data_ptr()`

In [31]:
b = a.view(3, 3)
print(b)

# From documentation, data_ptr() returns the address of the first element of
# self tensor
print(b.data_ptr())
print(a.data_ptr())

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
94101662774400
94101662774400


1b) Create a tensor `c = b[1:, 1:]`.   Predict and then check the size, offset, and stride.

The above slice is removal of the first item, followed by removal of the first item from the last two list items.

* Size: (2, 2).  
* Offset: 4, since we skip 0, 1, 2, and 3 to get to the first item in the list.
* Stride: (3, 1)

In [32]:
c = b[1:, 1:]
print(c)
print(f'Size of c = {c.size()}')
print(f'Offset of c = {c.storage_offset()}')
print(f'Stride of c = {c.stride()}')
print(c.data_ptr())

tensor([[4, 5],
        [7, 8]])
Size of c = torch.Size([2, 2])
Offset of c = 4
Stride of c = (3, 1)
94101662774432


Pick a mathematical operation like cosine or square root.  Can you find a corresponding function in the `torch` library?

In [40]:
b.square()

tensor([[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]])